---
- name: create_domain | configuring samba
  become_user: root
  template:
    src: etc/samba/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    roup: root
    mode: 0644
  notify:
    - restart nmbd
    - restart smbd
    - restart samba-ad-dc


- name: create_domain | configuring Active Directory
  shell: "samba-tool domain provision --server-role=dc --realm=PROGRESSOFT.CLOUD --dns-backend=SAMBA_INTERNAL --domain=PROGRESSOFT --adminpass=PSCloud@123  --use-rfc2307"
  become: true

  