---
- name: create_domain | configuring samba
  become_user: root
  template:
    src: etc/samba/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart nmbd
    - restart smbd
    - restart samba-ad-dc

- name: create_domain | checking if domain created
  stat:
    path: /var/log/.samba_ad_created
  register: samba_ad_created_check

- name: create_domain | configuring Active Directory
  shell: "samba-tool domain provision --server-role=dc --realm=PROGRESSOFT.CLOUD --dns-backend=SAMBA_INTERNAL --domain=PROGRESSOFT --adminpass='Win$ton123'  --use-rfc2307"
  become: true
- name: create_domain | marking domain as created
  file:
    dest: /var/log/.samba_ad_created
    state: touch
  become: true
  register: _samba_domain_created